services:
  postgres:
    container_name: pg-container
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: