name: Build and Release

run-name: Building and Releasing Version ${{ github.event.inputs.version }}

on:
  push:
    branches:
      - ci-setup
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          check-latest: true

      - name: Checkout app code
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Download Flutter dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release

      - name: Build Android Release AppBundle
        run: flutter build appbundle

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload Android AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-macos:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Verify Xcode version
        run: xcodebuild -version

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Download Flutter dependencies
        run: flutter pub get

      - name: Install Apple certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      
      - name: Install Apple provisioning profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp $PP_PATH ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Create DMG for macOS Release
        run: |
          create-dmg build/macos/Build/Products/Release/expense_manager.app --dmg-title "Expense Manager" build/macos/Build/Products/Release
          find build/macos/Build/Products/Release -name '*.dmg' -exec sh -c 'mv "$0" "build/macos/Build/Products/Release/expense-manager.dmg"' {} \;

      - name: Upload macOS DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-dmg
          path: build/macos/Build/Products/Release/expense-manager.dmg

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-macos]
    permissions:
      contents: write
      issues: write
    steps:
      - name: Download Android APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Download Android AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab

      - name: Download macOS DMG Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-macos-dmg

      - name: Create Release ${{ github.event.inputs.version }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "app-release.aab, app-release.apk, expense-manager.dmg"
          draft: true
          tag: ${{ github.event.inputs.version }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
