name: Build and Release

run-name: Building and Releasing Version ${{ github.event.inputs.version }}

on:
  push:
    branches:
      - ci-setup
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          check-latest: true

      - name: Checkout app code
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Download Flutter dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release

      - name: Build Android Release AppBundle
        run: flutter build appbundle

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload Android AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  release:
    runs-on: ubuntu-latest
    needs: [build-android]
    permissions:
      contents: write
      issues: write
    steps:
      - name: Download Android APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Download Android AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab

      - name: Create Release ${{ github.event.inputs.version }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "app-release.aab, app-release.apk"
          draft: true
          tag: ${{ github.event.inputs.version }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
